/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.erick.notification.fanout.rbmq;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.DeliverCallback;
import java.io.IOException;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author erickluz
 */
public class MQ extends javax.swing.JFrame {

    private String tagConsumer1 = "";
    private String tagConsumer2 = "";
    private Channel channelConsumer1 = getChannel();
    private Channel channelConsumer2 = getChannel();
    private Channel channelProducer;
    private Connection connectionMQ;
    private boolean isConsumerSetup = false;

    /**
     * Creates new form MQ
     */
    public MQ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsumer1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsumer2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        chkConsumer1 = new javax.swing.JCheckBox();
        chkConsumer2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnProduce = new javax.swing.JButton();
        txtProducer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumers"));

        txtConsumer1.setColumns(20);
        txtConsumer1.setRows(5);
        jScrollPane1.setViewportView(txtConsumer1);

        jLabel1.setText("Consumer 1:");

        txtConsumer2.setColumns(20);
        txtConsumer2.setRows(5);
        jScrollPane2.setViewportView(txtConsumer2);

        jLabel2.setText("Consumer 2:");

        chkConsumer1.setSelected(true);
        chkConsumer1.setText("Active");
        chkConsumer1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkConsumer1ItemStateChanged(evt);
            }
        });

        chkConsumer2.setSelected(true);
        chkConsumer2.setText("Active");
        chkConsumer2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkConsumer2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkConsumer1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkConsumer2)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(chkConsumer2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(chkConsumer1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Producer"));

        btnProduce.setText("Produce");
        btnProduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProducer, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduce)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduce)
                    .addComponent(txtProducer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduceActionPerformed
        sendMQ(txtProducer.getText());
    }//GEN-LAST:event_btnProduceActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (!isConsumerSetup) {
            setupConsumers();
            isConsumerSetup = true;
            connectRabbitMQ();
        }
    }//GEN-LAST:event_formWindowActivated

    private void chkConsumer1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkConsumer1ItemStateChanged
        if (chkConsumer1.isSelected()) {
            setupConsumers();
        } else {
            cancelConsumer(tagConsumer1, channelConsumer1);
            tagConsumer1 = "";
        }
    }//GEN-LAST:event_chkConsumer1ItemStateChanged

    private void chkConsumer2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkConsumer2ItemStateChanged
        if (chkConsumer2.isSelected()) {
            setupConsumers();
        } else {
            cancelConsumer(tagConsumer2, channelConsumer2);
            tagConsumer2 = "";
        }
    }//GEN-LAST:event_chkConsumer2ItemStateChanged

    private void cancelConsumer(String tagConsumer, Channel channel) {
        try {
            channel.basicCancel(tagConsumer);
        } catch (IOException ex) {
            Logger.getLogger(MQ.class.getName()).log(Level.SEVERE, "Erro to cancel consumer" + tagConsumer, ex);
        }
    }

    private void setupConsumers() {
        if (tagConsumer1.equals("") && chkConsumer1.isSelected()) {
            tagConsumer1 = setupConsumer(consumerOneCallback(), "one", channelConsumer1);
        }
        if (tagConsumer2.equals("") && chkConsumer2.isSelected()) {
            tagConsumer2 = setupConsumer(consumerTwoCallback(), "two", channelConsumer2);
        }
    }

    private static Connection getRabbitMQConnection() {
        try {
            return getFactory().newConnection();
        } catch (IOException ex) {
            Logger.getLogger(MQ.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TimeoutException ex) {
            Logger.getLogger(MQ.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private static Channel getChannel() {
        try {
            return getRabbitMQConnection().createChannel();
        } catch (IOException ex) {
            Logger.getLogger(MQ.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private String setupConsumer(DeliverCallback deliverCallback, String queue, Channel channel) {
        String tag = "";
        try {
            tag = channel.basicConsume(queue, true, deliverCallback, consumerTag -> {
            });
            Logger.getLogger(MQ.class.getName()).log(Level.INFO, "Consumer configured on queue: " + queue);
        } catch (Exception ex) {
            Logger.getLogger(MQ.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tag;
    }

    private DeliverCallback consumerOneCallback() {
        return (consumerTag, delivery) -> {
            this.txtConsumer1.append(new String(delivery.getBody(), "UTF-8") + "\n");
        };
    }

    private DeliverCallback consumerTwoCallback() {
        return (consumerTag, delivery) -> {
            this.txtConsumer2.append(new String(delivery.getBody(), "UTF-8") + "\n");
        };
    }

    private void connectRabbitMQ() {
        try {
            this.channelProducer = getFactory().newConnection().createChannel();
        } catch (Exception ex) {
            Logger.getLogger(MQ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void sendMQ(String value) {
        try {
            this.channelProducer.basicPublish("onetwo", "", null, value.getBytes());
        } catch (Exception e) {
            Logger.getLogger(MQ.class.getName()).log(Level.SEVERE, "Erro to send message", e);
        }
    }

    public static ConnectionFactory getFactory() {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("localhost");
        factory.setUsername("adm");
        factory.setPassword("adm");
        return factory;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProduce;
    private javax.swing.JCheckBox chkConsumer1;
    private javax.swing.JCheckBox chkConsumer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtConsumer1;
    private javax.swing.JTextArea txtConsumer2;
    private javax.swing.JTextField txtProducer;
    // End of variables declaration//GEN-END:variables

}
